### ISSUE TITLE
Add a way to set HTTP headers

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#124]
Searching for a way to conveniently overwrite existing or add new HTTP headers to requests.

Right now I can create a new `config.Config` with `config.NewConfiguration` or `config.DefaultConfiguration` but I'm only allowed to specify URL, user id, and token. The returned config will have `config.Config.userAgent` set for me automatically which is just one HTTP header.

Is there a convenient way for me to specify any custom header that is made during requests?

**Comment by nvthongswansea** [comment]
Could you show some use cases, please?

**Comment by bkircher** [comment]
I can give you two :slightly_smiling_face: 

- For instance content negotiation: imagine I have an end-point that reacts differently on User-Agent string so I'd need a way to change this when using the library
- Imagine gridscale API accepts additional or optional headers, that will change behavior on gridscale's side. I would want to set that header, too

**Comment by nvthongswansea** [comment]
I have 2 options for the next updates:
- Re-implementing the `NewConf()` function which will break the current version.
- Adding additional headers via env vars. This won't break anything.

**Comment by bkircher** [comment]
Are you sure we can't add new configuration options without breaking compatibility? This is a bit smelly and might need to get changed, right? Additions should not break compatibility. (At least not simple ones like adding new configuration options to an API.)

Environment variables obviously would work, but I think this might not be the best option/get out of hand. In the end, I want to use the client library itself to configure behavior. Not necessarily environment variables.

**Comment by nvthongswansea** [comment]
I am kinda sure that it will break the compatibility since we need to change the signature of the `NewConf()` function (not the `DefaultConf` one). Env vars can help us to get rid of that, but this option is not robust (to me). Actually there is an other way to deal with this which is to add a property to the `Config` struct and a method to set it directly. In my opinion, I don't see that a good practice as we have 2 functions for `Config` creation.

**Comment by bkircher** [comment]
I'm not arguing the fact that this change might break compatibility, but rather that this _should_ not break compatibility. Changing the signature of a public function every time a new configuration option is added is maybe not the right way to go.

Maybe we use this as an opportunity and change the code in a way so that configuration additions in future do not force us to introduce breaking changes?

**Comment by nvthongswansea** [comment]
That sounds ok to me. I think we need to create a new method to inject new headers to the `Conf`, which should be like `(c* Conf) WithHeaders(headers map[string]string) *Conf`. You can see one example in `http` package (find this line `(r *Request) WithContext(ctx context.Context) *Request` ).

**Comment by bkircher** [comment]
Sounds good and would be an idiomatic solution. :+1:

**Comment by fkr** [comment]
indeed that is a very good approach!
