### ISSUE TITLE
Move away from git flow

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#143]
Ditch git flow, use GitHub regular work flow. Will make releases much easier and we can automate with tools like [GoReleaser](https://goreleaser.com/).

TODO:

- [x] update CONTRIBUTING.md
- [x] update release-checklist.md
- [x] add goreleaser YAML
- [x] remote stale release branches from repository (`origin/release/*`)
- [X] remove develop branch, make master default

**Comment by bkircher** [comment]
All done here right?

**Comment by nvthongswansea** [comment]
Yep

**Comment by bkircher** [comment]
Well then, let's close it :wink:
