### ISSUE TITLE
Be able to create a new storage from a backup

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/gsclient-go#150]
API endpoint for creating a new storage from a specific backup: POST https://api.gridscale.io/objects/storages/import with `{"backup":{"name":"new storage","backup_uuid":"XXXX-XXXX-XXXX-XXXX-XXXX"}}` as a body. This functionality is not described in the official API docs yet.

**Comment by bkircher** [comment]
@nvthongswansea is there anything to be done here?

**Comment by bkircher** [comment]
Nevermind, too late
