### ISSUE TITLE
Weird relation

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#160]
:wave:  An IP object can be related to a storage? https://github.com/gridscale/gsclient-go/blob/master/ip.go#L113 `PublicIPs` and `Storages` seem to be always nil.

**Comment by nvthongswansea** [comment]
You are right. [Get IPs](https://gridscale.io/en/api-documentation/index.html#operation/getIps). I will change the label to bug. Thanks @bkircher
