### ISSUE TITLE
Make Q35 the default profile

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#161]
When creating servers and `ServerCreateRequest.ServerHardwareProfile` is omitted the resulting profile is pc-i440fx-2.4 which is a weird choice for a default.

When doing the same thing in the panel, I get pc-q35-2.10 (`"q35"` in the API docs) which is a much saner choice. Please consider changing default profile and set it explicitly to "q35". Also update the docs for `ServerCreateRequest.ServerHardwareProfile`, `"HardwareProfile is not set => server hardware is normal type"` is really not saying anything at all.

**Comment by nvthongswansea** [comment]
@bkircher is the server hardware profile set to "default" (as in https://gridscale.io/en/api-documentation/index.html#operation/createServer) when the `ServerCreateRequest.ServerHardwareProfile` is omitted?

**Comment by bkircher** [comment]
Yep. But that profile is pretty much useless. Also panel does select q35 if the user does not select anything else.

**Comment by nvthongswansea** [comment]
> Yep. But that profile is pretty much useless. Also panel does select q35 if the user does not select anything else.

I think this issue is from the backend side. Since the sdk just follows the API docs.

**Comment by bkircher** [comment]
> I think this issue is from the backend side.

Yep, absolutely. Meanwhile let's set a sensible default.

**Comment by MarcHarriss** [comment]
This is now default functionality via the API. The q35 hardware profile will now be set by default, therefore closing the issue.
