### ISSUE TITLE
API addition in GET /objects/paas/service_templates

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#174]
A heads up. There will be some updates to the `GET /objects/paas/service_templates` response.

A new `release` parameter will be included, and the `version` parameter will be modified from `version="10.3"` to `version="10.3-gs1"`.

For a postgres template example, it will look like:
```json
"9008f1f1-190e-4887-99f7-8a3e72fdd1f8": {
      "object_uuid": "9008f1f1-190e-4887-99f7-8a3e72fdd1f8",
      "release": "10.3",
      "version": "10.3-gs1",
      "name": "PostgreSQL 10.3 16GB (Gen 1)",
```

Current docs here: https://gridscale.io/en/api-documentation/index.html#operation/getPaasServiceTemplates

So I think we want to include that?

**Comment by nvthongswansea** [comment]
Sure.
