### ISSUE TITLE
Is a CLI client planned?

### ISSUE THREAD

**Issue by FabianTe** [gridscale/gsclient-go#86]
Hi there!

Is a CLI client planned, similar to how Azure CLi and so on work?

I ask since I would be interested in such a tool and would maybe like to contribute if you created this one open source.

*Please excuse me asking this on the Go Client. I just figured the Go client would be a great starting point for a CLI tool 😉*

**Comment by nvthongswansea** [comment]
Yes, the CLI client is under development (ofc it uses our `gsclient-go` :D).

**Comment by fkr** [comment]
Hi @FabianTe,

well, good place for the question, imho. 
Likely we're going to release a cli tool. However currently we have no ETA attached to that. Now that gsclient-go is feature-complete with the current API the focus is the terraform provider.

regards
felix
